In [1]:
import nltk

In [2]:
paragraph =  """Natural language processing (NLP) is a subfield of linguistics, computer science, information engineering, and artificial intelligence concerned with the interactions between computers and human (natural) languages, in particular how to program computers to process and analyze large amounts of natural language data.
                Challenges in natural language processing frequently involve speech recognition, natural language understanding, and natural-language generation. NLP is used as a method of personal development through promoting skills, such as self-reflection, confidence, and communication. Practitioners have applied NLP commercially to achieve work-orientated goals, such as improved productivity or job progression.
                Neuro-linguistic programming (NLP) is a pseudoscientific approach to communication, personal development, and psychotherapy created by Richard Bandler and John Grinder in California, United States, in the 1970s.
                What are the techniques of NLP?
                To understand this better, we list 5 techniques among the many NLP techniques you can use to elevate your coaching practice.
                1.Anchoring. This NLP technique is useful to regenerate a resourceful emotion. ...
                2.Belief Change. ...
                3.Mirroring and Rapport. ...
                4.Reframing Thoughts. ...
                5.Creative Visualization (Meditation, Hypnosis)
                In simple terms, NLP represents the automatic handling of natural human language like speech or text, and although the concept itself is fascinating, the real value behind this technology comes from the use cases.
                NLP can help you with lots of tasks and the fields of application just seem to increase on a daily basis. Let’s mention some examples:
                NLP enables the recognition and prediction of diseases based on electronic health records and patient’s own speech. This capability is being explored in health conditions that go from cardiovascular diseases to depression and even schizophrenia. For example, Amazon Comprehend Medical is a service that uses NLP to extract disease conditions, medications and treatment outcomes from patient notes, clinical trial reports and other electronic health records.
                Organizations can determine what customers are saying about a service or product by identifying and extracting information in sources like social media. This sentiment analysis can provide a lot of information about customers choices and their decision drivers.
                An inventor at IBM developed a cognitive assistant that works like a personalized search engine by learning all about you and then remind you of a name, a song, or anything you can’t remember the moment you need it to.
                Companies like Yahoo and Google filter and classify your emails with NLP by analyzing text in emails that flow through their servers and stopping spam before they even enter your inbox.
                To help identifying fake news, the NLP Group at MIT developed a new system to determine if a source is accurate or politically biased, detecting if a news source can be trusted or not.
                Amazon’s Alexa and Apple’s Siri are examples of intelligent voice driven interfaces that use NLP to respond to vocal prompts and do everything like find a particular shop, tell us the weather forecast, suggest the best route to the office or turn on the lights at home.
                Having an insight into what is happening and what people are talking about can be very valuable to financial traders. NLP is being used to track news, reports, comments about possible mergers between companies, everything can be then incorporated into a trading algorithm to generate massive profits. Remember: buy the rumor, sell the news.
                NLP is also being used in both the search and selection phases of talent recruitment, identifying the skills of potential hires and also spotting prospects before they become active on the job market.
                Powered by IBM Watson NLP technology, LegalMation developed a platform to automate routine litigation tasks and help legal teams save time, drive down costs and shift strategic focus."""

In [3]:
# Cleaning the texts
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

ps = PorterStemmer()
wordnet=WordNetLemmatizer()
sentences = nltk.sent_tokenize(paragraph)
corpus = []
for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z]', ' ', sentences[i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [7]:
print(corpus)

['natur languag process nlp subfield linguist comput scienc inform engin artifici intellig concern interact comput human natur languag particular program comput process analyz larg amount natur languag data', 'challeng natur languag process frequent involv speech recognit natur languag understand natur languag gener', 'nlp use method person develop promot skill self reflect confid commun', 'practition appli nlp commerci achiev work orient goal improv product job progress', 'neuro linguist program nlp pseudoscientif approach commun person develop psychotherapi creat richard bandler john grinder california unit state', 'techniqu nlp', 'understand better list techniqu among mani nlp techniqu use elev coach practic', 'anchor', 'nlp techniqu use regener resourc emot', 'belief chang', 'mirror rapport', 'refram thought', 'creativ visual medit hypnosi simpl term nlp repres automat handl natur human languag like speech text although concept fascin real valu behind technolog come use case', 'nlp

In [4]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()

In [5]:
print(cv)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=1500, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)


In [6]:
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [14]:
X.shape

(28, 258)